Import potrzebnych modółów <br>
1 numpy <br>
2 sys <br>

In [ ]:
import numpy as np
import sys

In [13]:
a = np.array([1, 2, 3, 4, 5], dtype="int16") # Mozemy decydowac o typie danych w macierzy oraz jej wielkosci
print ("a:\n", a)
b = np.array([6.0, 7.0, 8.0, 9.0, 10.0])
print ("b:\n", b)
c = np.array([[1, 2, 3], [4, 5, 6]])
print ("c: \n", c)

print("\n\n")
# Takie macierze mozna badac pod koatem wymarow , przyklad ponizej:
print("Wymiar macierzy a:")
print(a.ndim)    # liczba wymiarow ndim = number of dimensions
print("Ksztalt macierzy c:")
print(c.shape)  # shape = ksztalt macierzy, czyli liczba wierszy i kolumn

print("Typ danych w macierzy a i b:")
print(a.dtype)  # dtype = typ danych w macierzy
print(b.dtype)  # typ danych w macierzy b

a:
 [1 2 3 4 5]
b:
 [ 6.  7.  8.  9. 10.]
c: 
 [[1 2 3]
 [4 5 6]]



Wymiar macierzy a:
1
Ksztalt macierzy c:
(2, 3)
Typ danych w macierzy a i b:
int16
float64
