Import potrzebnych modółów <br>
1 numpy <br>
Materiał zdobyty z kanału https://www.youtube.com/watch?v=QUT1VHiLmmI&t=986s

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5], dtype="int8") # Mozemy decydowac o typie danych w macierzy oraz jej wielkosci
print ("a:\n", a)
b = np.array([6.0, 7.0, 8.0, 9.0, 10.0])
print ("b:\n", b)
c = np.array([[1, 2, 3], [4, 5, 6]])
print ("c: \n", c)

print("\n\n")
# Takie macierze mozna badac pod koatem wymarow , przyklad ponizej:
print("Wymiar macierzy a:")
print(a.ndim)    # liczba wymiarow ndim = number of dimensions
print("Ksztalt macierzy c:")
print(c.shape)  # shape = ksztalt macierzy, czyli liczba wierszy i kolumn
print()

print("Typ danych w macierzy a i b:")
print(a.dtype)  # dtype = typ danych w macierzy
print(b.dtype)  # typ danych w macierzy b
print()

print("Sprawdzenie rozmiarow zajetej przez 1 element pamieci macierzy a i b:")
print(a.itemsize)  # itemsize = rozmiar pojedynczego elementu macierzy w bajtach
print(b.itemsize)  # rozmiar pojedynczego elementu macierzy b w bajtach
print(b.itemsize * b.size)  # rozmiar calej macierzy b w bajtach. Da sie to zrobic tez za pomoca b.nbytes
print()

print("Wybieranie elementow macierzy:")
print("Pierwszy element macierzy c:", c[0,0])  # pierwszy element macierzy c
print("Pierwszy wiersz macierzy c:", c[0])  # pierwszy wiersz macierzy c
print("Pierwsza kolumna macierzy c:", c[:,0])  # pierwsza kolumna macierzy c
print("Co drugi element macierzy c:", c[:,::2])  # co drugi wiersz macierzy c

print('\nTworzenie rożnuych macierzy:')
d = np.zeros((2,2,2), dtype="int8")  # macierz zerowa o wymiarach 2x2x2
print("Macierz zerowa d:\n", d)
print
e = np.ones((2,2,2),dtype="int8")  # macierz jedynkowa o wymiarach 2x2x2
print("Macierz jedynkowa e:\n", e)

f = np.full((2,2), 7, dtype="int8")  # macierz wypelniona liczba 7 o wymiarach 2x2
print("Macierz wypelniona liczba 7:\n", f)

a:
 [1 2 3 4 5]
b:
 [ 6.  7.  8.  9. 10.]
c: 
 [[1 2 3]
 [4 5 6]]



Wymiar macierzy a:
1
Ksztalt macierzy c:
(2, 3)

Typ danych w macierzy a i b:
int8
float64

Sprawdzenie rozmiarow zajetej przez 1 element pamieci macierzy a i b:
1
8
40

Wybieranie elementow macierzy:
Pierwszy element macierzy c: 1
Pierwszy wiersz macierzy c: [1 2 3]
Pierwsza kolumna macierzy c: [1 4]
Co drugi element macierzy c: [[1 3]
 [4 6]]

Tworzenie rożnuych macierzy:
Macierz zerowa d:
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
Macierz jedynkowa e:
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
Macierz wypelniona liczba 7:
 [[7 7]
 [7 7]]


Nowa linijka kodu, z powodu czytelności kodu <div>


In [13]:
z = np.random.random((2,2))  # macierz wypelniona losowymi liczbami z przedzialu [0,1) o wymiarach 2x2
print("Macierz losowa z:\n", z)
x = np.random.randint(0, 10, (2,2),dtype="int16")  # macierz wypelniona losowymi liczbami calkowitymi z przedzialu [0,10) o wymiarach 2x2
print("Macierz losowa calkowita x:\n", x)
c = np.random.randint(0, 10, (2,2,2))  # macierz wypelniona losowymi liczbami calkowitymi z przedzialu [0,10) o wymiarach 2x2x2
print("Macierz losowa calkowita c:\n", c)
v = np.random.randint(7,size=(3,3))  # macierz wypelniona losowymi liczbami calkowitymi z przedzialu [0,7) o wymiarach 3x3
print("Macierz losowa calkowita v:\n", v)

print("\n\n")

q = np.array([[1,2,3]])
r1 = np.repeat(q,3,axis=0)  # powtarzanie elementow macierzy q 3 razy w osi 0
print("Powtarzanie elementow macierzy q 3 razy w osi 0:\n", r1)

Macierz losowa z:
 [[0.39714986 0.81342263]
 [0.64177544 0.41442571]]
Macierz losowa calkowita x:
 [[7 4]
 [5 3]]
Macierz losowa calkowita c:
 [[[6 5]
  [1 5]]

 [[7 8]
  [4 3]]]
Macierz losowa calkowita v:
 [[6 6 4]
 [2 1 4]
 [1 6 2]]



Powtarzanie elementow macierzy q 3 razy w osi 0:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


Probowanie tworzenia kształtów

In [ ]:
sample1 = np.ones([5,5], dtype="int8")  # tworzenie macierzy jedynkowej o wymiarach 5x5
sample2 = np.zeros((3,3), dtype="int8")  # tworzenie macierzy zerowej o wymiarach 3x3
sample2[1,1] = 9  # ustawienie wartosci 9 w srodku macierzy sample2
sample1[1:4,1:4] = sample2  # wstawienie macierzy sample2 do macierzy sample1
print("Wstawienie macierzy sample2 do macierzy sample1:\n", sample1) 

Wstawienie macierzy sample2 do macierzy sample1:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Formatowanie macierzy <div>


In [15]:
przed = np.array([[1,2,3,4],[5,6,7,8]])
po = przed.reshape(1,8) # zmiana ksztaltu macierzy przed na macierz o wymiarach 1x8
print("Zmiana ksztaltu macierzy przed na macierz o wymiarach 1x8:\n", po)
print("Sprawdzenie czy macierz przed i po sa takie same:\n", np.array_equal(przed, po))  # sprawdzenie czy macierz przed i po sa takie same

print("\n")
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

print("Pionowe laczenie macierzy v1 i v2:\n", np.vstack((v1, v2)))
print("Poziome laczenie macierzy v1 i v2:\n", np.hstack((v1, v2)))  # poziome laczenie macierzy v1 i v2

Zmiana ksztaltu macierzy przed na macierz o wymiarach 1x8:
 [[1 2 3 4 5 6 7 8]]
Sprawdzenie czy macierz przed i po sa takie same:
 False


Pionowe laczenie macierzy v1 i v2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Poziome laczenie macierzy v1 i v2:
 [ 1  2  3  4  5  6  7  8  9 10]
